// Mock Data and Domain Models for SahakarGig Platform (SIH26089)

export const SERVICES_CATALOG = [
  {
    id: 'plumbing',
    title: 'Plumbing & Water Systems',
    titleHi: 'प्लंबिंग एवं जल सेवाएं',
    icon: 'Wrench',
    category: 'Essential Maintenance',
    basePrice: 299,
    estimatedDuration: '45-60 mins',
    popular: true,
    description: 'Expert pipe leakage repair, bathroom fittings, tap replacement, drainage unclogging & motor servicing.',
    workerSharePercent: 88,
    welfareSharePercent: 7,
    platformSharePercent: 5,
    subServices: [
      { id: 'p1', name: 'Tap & Shower Leakage Fix', price: 299, duration: '40m' },
      { id: 'p2', name: 'Bathroom Drain Jet Unclogging', price: 499, duration: '60m' },
      { id: 'p3', name: 'Water Tank & Pipe Installation', price: 899, duration: '120m' },
      { id: 'p4', name: 'Water Pump / Motor Repair', price: 549, duration: '75m' },
    ]
  },
  {
    id: 'electrical',
    title: 'Electrical & Power Systems',
    titleHi: 'इलेक्ट्रिकल एवं वायरिंग',
    icon: 'Zap',
    category: 'Essential Maintenance',
    basePrice: 349,
    estimatedDuration: '30-45 mins',
    popular: true,
    description: 'Certified electricians for short-circuit diagnosis, fan/geyser repair, switchboard installation, and safety earthing.',
    workerSharePercent: 88,
    welfareSharePercent: 7,
    platformSharePercent: 5,
    subServices: [
      { id: 'e1', name: 'Switchboard & Socket Installation', price: 349, duration: '30m' },
      { id: 'e2', name: 'Ceiling Fan / Exhaust Fan Repair', price: 399, duration: '45m' },
      { id: 'e3', name: 'MCB / Short Circuit Troubleshooting', price: 499, duration: '60m' },
      { id: 'e4', name: 'Geyser / Water Heater Repair', price: 599, duration: '60m' },
    ]
  },
  {
    id: 'ac-repair',
    title: 'AC Service & Climate Tech',
    titleHi: 'एसी रिपेयर एवं सर्विसिंग',
    icon: 'Wind',
    category: 'Appliance Care',
    basePrice: 599,
    estimatedDuration: '60-90 mins',
    popular: true,
    description: 'Eco-friendly foam jet AC cleaning, cooling coil diagnosis, gas refilling, and anti-bacterial filter sanitation.',
    workerSharePercent: 87,
    welfareSharePercent: 8,
    platformSharePercent: 5,
    subServices: [
      { id: 'ac1', name: 'Deep Jet Power AC Servicing', price: 599, duration: '60m' },
      { id: 'ac2', name: 'Refrigerant Gas Leak Fix & Refill', price: 1899, duration: '90m' },
      { id: 'ac3', name: 'Split AC Uninstallation / Relocation', price: 899, duration: '90m' },
    ]
  },
  {
    id: 'deep-cleaning',
    title: 'Deep House Sanitization',
    titleHi: 'सम्पूर्ण गृह स्वच्छता सेवा',
    icon: 'Sparkles',
    category: 'Housekeeping',
    basePrice: 899,
    estimatedDuration: '2-3 hours',
    popular: false,
    description: 'Hospital-grade mechanized deep cleaning for kitchens, bathrooms, sofas, balconies, and full apartments.',
    workerSharePercent: 88,
    welfareSharePercent: 7,
    platformSharePercent: 5,
    subServices: [
      { id: 'c1', name: 'Kitchen Chimney & Tile Degreasing', price: 899, duration: '90m' },
      { id: 'c2', name: 'Intense Bathroom Descaling (2 Bathrooms)', price: 799, duration: '80m' },
      { id: 'c3', name: 'Full 2BHK Deep Sanitization Package', price: 2499, duration: '180m' },
    ]
  },
  {
    id: 'carpentry',
    title: 'Carpentry & Woodcraft',
    titleHi: 'बढ़ईगीरी एवं फर्नीचर मरम्मत',
    icon: 'Hammer',
    category: 'Specialized Trades',
    basePrice: 399,
    estimatedDuration: '45-60 mins',
    popular: false,
    description: 'Skilled woodworkers for lock installations, door alignments, modular kitchen repairs, and custom shelves.',
    workerSharePercent: 88,
    welfareSharePercent: 7,
    platformSharePercent: 5,
    subServices: [
      { id: 'cp1', name: 'Door Lock / Latch Replacement', price: 399, duration: '40m' },
      { id: 'cp2', name: 'Modular Cabinet Hinge Repair', price: 449, duration: '45m' },
      { id: 'cp3', name: 'Custom Wall Shelf / TV Mount', price: 599, duration: '60m' },
    ]
  },
  {
    id: 'appliance-repair',
    title: 'Major Home Appliances',
    titleHi: 'घरेलू उपकरण मरम्मत',
    icon: 'Cpu',
    category: 'Appliance Care',
    basePrice: 449,
    estimatedDuration: '45-75 mins',
    popular: false,
    description: 'Fast diagnostics for refrigerators, washing machines, microwave ovens, and RO water purifiers with genuine parts.',
    workerSharePercent: 87,
    welfareSharePercent: 8,
    platformSharePercent: 5,
    subServices: [
      { id: 'ap1', name: 'Washing Machine Drum / Motor Fix', price: 649, duration: '60m' },
      { id: 'ap2', name: 'Refrigerator Cooling & Thermostat Fix', price: 599, duration: '60m' },
      { id: 'ap3', name: 'RO Water Purifier Filter Service', price: 449, duration: '45m' },
    ]
  },
  {
    id: 'painting',
    title: 'Painting & Damp Treatment',
    titleHi: 'पेंटिंग एवं वॉटरप्रूफिंग',
    icon: 'Paintbrush',
    category: 'Renovation',
    basePrice: 799,
    estimatedDuration: '1-2 days',
    popular: false,
    description: 'Wall touch-ups, accent texture painting, anti-fungal waterproofing, and exterior protective coating.',
    workerSharePercent: 89,
    welfareSharePercent: 6,
    platformSharePercent: 5,
    subServices: [
      { id: 'pt1', name: 'Single Room Accent Wall Painting', price: 1499, duration: '180m' },
      { id: 'pt2', name: 'Balcony / Wall Damp Proof Treatment', price: 999, duration: '120m' },
    ]
  },
  {
    id: 'elder-assistance',
    title: 'Elder & Mobility Support',
    titleHi: 'वरिष्ठ नागरिक सहायता',
    icon: 'HeartHandshake',
    category: 'Care Services',
    basePrice: 349,
    estimatedDuration: '60 mins',
    popular: false,
    description: 'Trained cooperative community caregivers for mobility assistance, medical appointments, and daily errand support.',
    workerSharePercent: 90,
    welfareSharePercent: 6,
    platformSharePercent: 4,
    subServices: [
      { id: 'ea1', name: 'Doctor Visit & Mobility Chaperone (2 hrs)', price: 499, duration: '120m' },
      { id: 'ea2', name: 'Grocery & Prescription Errand Support', price: 349, duration: '60m' },
    ]
  }
];

export const INITIAL_WORKERS = [
  // 1. Ramesh Jadhav (Electrical & Appliances - Shivajinagar)
  {
    id: 'w-101',
    name: 'Ramesh Jadhav',
    nameHi: 'रमेश जाधव',
    email: 'ramesh.jadhav@coop.org',
    phone: '+91 98230 44819',
    avatar: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
    skills: ['electrical', 'appliance-repair'],
    experienceYears: 7,
    rating: 4.9,
    hourlyRate: 249,
    visitingCharge: 149,
    totalJobsCompleted: 438,
    cooperativeMemberId: 'MH-PUN-ELEC-001',
    societyName: 'Pune Urban Electrical & Tech Cooperative Society',
    location: { lat: 18.5204, lng: 73.8567, address: 'Shivajinagar, Pune' },
    status: 'online',
    isOnline: true,
    fairRotationScore: 94,
    certification: 'NSDC Level 4 Certified Electrician',
    aadhaarVerified: true,
    skillIndiaBadge: true,
    languages: ['Hindi', 'Marathi', 'English'],
    wallet: { grossEarnings: 38450, availableBalance: 4620, patronageDividends: 3120, welfarePoints: 850, emergencyFundReserved: 1400 }
  },
  // 2. Sunita Patil (Deep Cleaning & Elder Care - FC Road)
  {
    id: 'w-102',
    name: 'Sunita Patil',
    nameHi: 'सुनीता पाटिल',
    email: 'sunita.patil@coop.org',
    phone: '+91 97654 11209',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    skills: ['deep-cleaning', 'elder-assistance'],
    experienceYears: 5,
    rating: 4.95,
    hourlyRate: 199,
    visitingCharge: 99,
    totalJobsCompleted: 312,
    cooperativeMemberId: 'MH-PUN-CLEAN-019',
    societyName: 'Mahila Swavalamban Cooperative Society',
    location: { lat: 18.5314, lng: 73.8446, address: 'FC Road, Pune' },
    status: 'online',
    isOnline: true,
    fairRotationScore: 98,
    certification: 'Govt. Certified Sanitization Specialist',
    aadhaarVerified: true,
    skillIndiaBadge: true,
    languages: ['Marathi', 'Hindi'],
    wallet: { grossEarnings: 29800, availableBalance: 3450, patronageDividends: 2450, welfarePoints: 920, emergencyFundReserved: 1100 }
  },
  // 3. Mohammad Tariq (Plumbing & Appliances - Kothrud)
  {
    id: 'w-103',
    name: 'Mohammad Tariq',
    nameHi: 'मोहम्मद तारिक',
    email: 'mohammad.tariq@coop.org',
    phone: '+91 99221 88340',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    skills: ['plumbing', 'appliance-repair'],
    experienceYears: 9,
    rating: 4.85,
    hourlyRate: 219,
    visitingCharge: 129,
    totalJobsCompleted: 580,
    cooperativeMemberId: 'MH-PUN-PLUMB-007',
    societyName: 'Sahyadri Plumbing & Maintenance Workers Coop',
    location: { lat: 18.5089, lng: 73.8258, address: 'Kothrud, Pune' },
    status: 'online',
    isOnline: true,
    fairRotationScore: 89,
    certification: 'Master Plumber Certification (ITI Pune)',
    aadhaarVerified: true,
    skillIndiaBadge: true,
    languages: ['Hindi', 'Urdu', 'Marathi'],
    wallet: { grossEarnings: 49200, availableBalance: 6100, patronageDividends: 4200, welfarePoints: 1100, emergencyFundReserved: 1800 }
  },
  // 4. Vikram Singh (Electrical & AC Repair - Baner)
  {
    id: 'w-104',
    name: 'Vikram Singh',
    nameHi: 'विक्रम सिंह',
    email: 'vikram.singh@coop.org',
    phone: '+91 98812 77019',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    skills: ['ac-repair', 'electrical'],
    experienceYears: 6,
    rating: 4.88,
    hourlyRate: 299,
    visitingCharge: 179,
    totalJobsCompleted: 390,
    cooperativeMemberId: 'MH-PUN-ELEC-002',
    societyName: 'Maharashtra HVAC & Electrical Technicians Cooperative',
    location: { lat: 18.5590, lng: 73.7868, address: 'Baner, Pune' },
    status: 'online',
    isOnline: true,
    fairRotationScore: 91,
    certification: 'BEE Certified Energy Efficient Specialist',
    aadhaarVerified: true,
    skillIndiaBadge: true,
    languages: ['Hindi', 'English', 'Punjabi'],
    wallet: { grossEarnings: 42100, availableBalance: 5200, patronageDividends: 3600, welfarePoints: 790, emergencyFundReserved: 1550 }
  },
  // 5. Anand Shinde (Carpentry & Painting - Karve Nagar)
  {
    id: 'w-105',
    name: 'Anand Shinde',
    nameHi: 'आनंद शिंदे',
    email: 'anand.shinde@coop.org',
    phone: '+91 98220 99411',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    skills: ['carpentry', 'painting'],
    experienceYears: 11,
    rating: 4.92,
    hourlyRate: 269,
    visitingCharge: 159,
    totalJobsCompleted: 640,
    cooperativeMemberId: 'MH-PUN-WOOD-012',
    societyName: 'Shree Ganesh Woodcraft Cooperative',
    location: { lat: 18.5074, lng: 73.8077, address: 'Karve Nagar, Pune' },
    status: 'online',
    isOnline: true,
    fairRotationScore: 95,
    certification: 'NSDC Certified Master Carpenter',
    aadhaarVerified: true,
    skillIndiaBadge: true,
    languages: ['Marathi', 'Hindi'],
    wallet: { grossEarnings: 53800, availableBalance: 7300, patronageDividends: 4890, welfarePoints: 1250, emergencyFundReserved: 2100 }
  },
  // 6. Sachin Bhosale (Electrical - Kothrud)
  {
    id: 'w-106',
    name: 'Sachin Bhosale',
    nameHi: 'सचिन भोसले',
    email: 'sachin.bhosale@coop.org',
    phone: '+91 98221 64510',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    skills: ['electrical'],
    experienceYears: 8,
    rating: 4.92,
    hourlyRate: 249,
    visitingCharge: 149,
    totalJobsCompleted: 382,
    cooperativeMemberId: 'MH-PUN-ELEC-003',
    societyName: 'Kothrud Artisan Guild & Electrical Coop',
    location: { lat: 18.5020, lng: 73.8120, address: 'Kothrud Ward, Pune' },
    status: 'online',
    isOnline: true,
    fairRotationScore: 96,
    certification: 'Govt. Licensed Wireman Grade A',
    aadhaarVerified: true,
    skillIndiaBadge: true,
    languages: ['Marathi', 'Hindi'],
    wallet: { grossEarnings: 36200, availableBalance: 4100, patronageDividends: 2800, welfarePoints: 720, emergencyFundReserved: 1200 }
  },
  // 7. Mahesh Shinde (Electrical - Deccan Gymkhana)
  {
    id: 'w-107',
    name: 'Mahesh Shinde',
    nameHi: 'महेश शिंदे',
    email: 'mahesh.shinde@coop.org',
    phone: '+91 98902 43190',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    skills: ['electrical'],
    experienceYears: 5,
    rating: 4.85,
    hourlyRate: 239,
    visitingCharge: 139,
    totalJobsCompleted: 248,
    cooperativeMemberId: 'MH-PUN-ELEC-004',
    societyName: 'Deccan Wiremen & Maintenance Coop',
    location: { lat: 18.5167, lng: 73.8415, address: 'Deccan Gymkhana, Pune' },
    status: 'online',
    isOnline: true,
    fairRotationScore: 92,
    certification: 'ITI Industrial Electrician Certified',
    aadhaarVerified: true,
    skillIndiaBadge: true,
    languages: ['Marathi', 'Hindi', 'English'],
    wallet: { grossEarnings: 28400, availableBalance: 3200, patronageDividends: 2100, welfarePoints: 640, emergencyFundReserved: 900 }
  },
  // 8. Rajesh Kulkarni (Electrical & Appliances - Aundh)
  {
    id: 'w-108',
    name: 'Rajesh Kulkarni',
    nameHi: 'राजेश कुलकर्णी',
    email: 'rajesh.kulkarni@coop.org',
    phone: '+91 97651 88204',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    skills: ['electrical', 'appliance-repair'],
    experienceYears: 9,
    rating: 4.90,
    hourlyRate: 259,
    visitingCharge: 149,
    totalJobsCompleted: 495,
    cooperativeMemberId: 'MH-PUN-ELEC-005',
    societyName: 'Aundh Smart Power & Wiring Society',
    location: { lat: 18.5580, lng: 73.8074, address: 'Aundh Gaon, Pune' },
    status: 'online',
    isOnline: true,
    fairRotationScore: 97,
    certification: 'NSDC Master Electrician Certified',
    aadhaarVerified: true,
    skillIndiaBadge: true,
    languages: ['Marathi', 'Hindi', 'English'],
    wallet: { grossEarnings: 44100, availableBalance: 5900, patronageDividends: 3900, welfarePoints: 980, emergencyFundReserved: 1600 }
  },
  // 9. Amit Deshmukh (Electrical - Viman Nagar)
  {
    id: 'w-109',
    name: 'Amit Deshmukh',
    nameHi: 'अमित देशमुख',
    email: 'amit.deshmukh@coop.org',
    phone: '+91 98234 19823',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    skills: ['electrical'],
    experienceYears: 4,
    rating: 4.87,
    hourlyRate: 249,
    visitingCharge: 149,
    totalJobsCompleted: 215,
    cooperativeMemberId: 'MH-PUN-ELEC-006',
    societyName: 'Viman Nagar Power Tech Workers Coop',
    location: { lat: 18.5679, lng: 73.9143, address: 'Viman Nagar, Pune' },
    status: 'online',
    isOnline: true,
    fairRotationScore: 90,
    certification: 'Govt. Safety Earthing & Circuit Certified',
    aadhaarVerified: true,
    skillIndiaBadge: true,
    languages: ['Hindi', 'Marathi', 'English'],
    wallet: { grossEarnings: 24100, availableBalance: 2900, patronageDividends: 1800, welfarePoints: 580, emergencyFundReserved: 800 }
  },
  // 10. Ganesh More (Electrical - Hadapsar)
  {
    id: 'w-110',
    name: 'Ganesh More',
    nameHi: 'गणेश मोरे',
    email: 'ganesh.more@coop.org',
    phone: '+91 98603 55192',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    skills: ['electrical'],
    experienceYears: 10,
    rating: 4.89,
    hourlyRate: 249,
    visitingCharge: 149,
    totalJobsCompleted: 520,
    cooperativeMemberId: 'MH-PUN-ELEC-007',
    societyName: 'Swargate & Hadapsar Electricians Guild',
    location: { lat: 18.5089, lng: 73.9260, address: 'Hadapsar Magarpatta, Pune' },
    status: 'online',
    isOnline: true,
    fairRotationScore: 93,
    certification: 'NSDC Level 4 High Tension Certified',
    aadhaarVerified: true,
    skillIndiaBadge: true,
    languages: ['Marathi', 'Hindi'],
    wallet: { grossEarnings: 47900, availableBalance: 6400, patronageDividends: 4100, welfarePoints: 1050, emergencyFundReserved: 1750 }
  },
  // 11. Nitin Pawar (Electrical & Appliances - Wakad)
  {
    id: 'w-111',
    name: 'Nitin Pawar',
    nameHi: 'नितिन पवार',
    email: 'nitin.pawar@coop.org',
    phone: '+91 98229 33718',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    skills: ['electrical', 'appliance-repair'],
    experienceYears: 7,
    rating: 4.91,
    hourlyRate: 259,
    visitingCharge: 149,
    totalJobsCompleted: 360,
    cooperativeMemberId: 'MH-PUN-ELEC-008',
    societyName: 'PCMC & Wakad Electrical Artisans Coop',
    location: { lat: 18.5987, lng: 73.7684, address: 'Wakad Bridge, Pune' },
    status: 'online',
    isOnline: true,
    fairRotationScore: 95,
    certification: 'Certified Domestic Power Safety Auditor',
    aadhaarVerified: true,
    skillIndiaBadge: true,
    languages: ['Marathi', 'Hindi', 'English'],
    wallet: { grossEarnings: 39500, availableBalance: 4800, patronageDividends: 3200, welfarePoints: 890, emergencyFundReserved: 1450 }
  },
  // 12. Pradeep Salunkhe (Electrical - Pune Camp)
  {
    id: 'w-112',
    name: 'Pradeep Salunkhe',
    nameHi: 'प्रदीप साळुंखे',
    email: 'pradeep.salunkhe@coop.org',
    phone: '+91 97640 12895',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    skills: ['electrical'],
    experienceYears: 8,
    rating: 4.86,
    hourlyRate: 249,
    visitingCharge: 139,
    totalJobsCompleted: 410,
    cooperativeMemberId: 'MH-PUN-ELEC-009',
    societyName: 'Camp & Pune Station Guild of Technicians',
    location: { lat: 18.5135, lng: 73.8784, address: 'MG Road, Pune Camp' },
    status: 'online',
    isOnline: true,
    fairRotationScore: 92,
    certification: 'ITI Electrical & Energy Audit Specialist',
    aadhaarVerified: true,
    skillIndiaBadge: true,
    languages: ['Hindi', 'Marathi', 'English'],
    wallet: { grossEarnings: 37800, availableBalance: 4400, patronageDividends: 2950, welfarePoints: 830, emergencyFundReserved: 1300 }
  },
  // 13. Deepak Gaikwad (Electrical - Sinhagad Road)
  {
    id: 'w-113',
    name: 'Deepak Gaikwad',
    nameHi: 'दीपक गायकवाड',
    email: 'deepak.gaikwad@coop.org',
    phone: '+91 98501 77340',
    avatar: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=150&auto=format&fit=crop&q=80',
    skills: ['electrical'],
    experienceYears: 6,
    rating: 4.93,
    hourlyRate: 249,
    visitingCharge: 149,
    totalJobsCompleted: 345,
    cooperativeMemberId: 'MH-PUN-ELEC-010',
    societyName: 'Sinhagad Road Powerline Technicians Coop',
    location: { lat: 18.4789, lng: 73.8245, address: 'Sinhagad Road, Pune' },
    status: 'online',
    isOnline: true,
    fairRotationScore: 96,
    certification: 'NSDC Certified Power Systems Expert',
    aadhaarVerified: true,
    skillIndiaBadge: true,
    languages: ['Marathi', 'Hindi'],
    wallet: { grossEarnings: 33900, availableBalance: 3950, patronageDividends: 2700, welfarePoints: 770, emergencyFundReserved: 1250 }
  }
];

export const INITIAL_PROPOSALS = [
  {
    id: 'prop-2026-01',
    title: 'Monsoon Safety Equipment & Tool Subsidy Grant',
    titleHi: 'मानसून सुरक्षा किट एवं उपकरण अनुदान',
    category: 'Welfare & Safety',
    proposedBy: 'Worker Advisory Council (Pune Central)',
    description: 'Allocate ₹1,85,000 from the Collective Welfare Reserve to distribute insulated boots, raincoat gear, and surge testers to 200 active electrical & plumbing workers.',
    status: 'active', // 'active' | 'passed' | 'rejected'
    yesVotes: 142,
    noVotes: 11,
    totalEligibleVoters: 180,
    deadline: '2026-09-15',
    fundImpact: '₹1,85,000 from Welfare Reserve',
    hasVoted: false
  },
  {
    id: 'prop-2026-02',
    title: 'Revision of Base Floor Wage for Emergency Night Dispatches (8 PM - 6 AM)',
    titleHi: 'रात्रिकालीन आपातकालीन सेवा न्यूनतम दर में वृद्धि',
    category: 'Pricing & Wages',
    proposedBy: 'HVAC & Electrical Guild',
    description: 'Mandate a minimum 25% hazard & overtime surge on all night calls, 100% of which directly flows to the on-duty worker.',
    status: 'active',
    yesVotes: 168,
    noVotes: 4,
    totalEligibleVoters: 180,
    deadline: '2026-09-01',
    fundImpact: '+25% direct worker payout increment',
    hasVoted: true
  },
  {
    id: 'prop-2026-03',
    title: 'Zero-Interest Micro-Credit Facility for Electric Bike Purchase',
    titleHi: 'ई-बाइक खरीद हेतु ब्याज मुक्त माइक्रो-लोन योजना',
    category: 'Green Mobility & Loans',
    proposedBy: 'Board of Directors',
    description: 'Partner with District Cooperative Bank to offer ₹40,000 zero-interest soft loans to high-performing gig workers for transitioning to EV two-wheelers.',
    status: 'passed',
    yesVotes: 174,
    noVotes: 6,
    totalEligibleVoters: 180,
    deadline: '2026-08-10',
    fundImpact: 'Cooperative Credit Guarantee backed by PACS',
    hasVoted: true
  }
];

export const INITIAL_DISPUTES = [
  {
    id: 'disp-801',
    bookingId: 'BK-9912',
    customerName: 'Dr. Alok Verma',
    workerName: 'Vikram Singh',
    service: 'AC Jet Servicing',
    amount: 599,
    date: '2026-08-21',
    issueCategory: 'Quality of Service',
    description: 'Customer claims water leakage occurred from indoor unit 2 hours after service.',
    workerStatement: 'Drain pipe was cleared and inspected with video proof. Leakage appears from internal wall condensation crack.',
    evidenceUrls: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=300'],
    status: 'pending_jury',
    juryMembers: ['Sunita Patil (Peer)', 'Mohammad Tariq (Peer)', 'Coop Mediator'],
    verdict: null
  },
  {
    id: 'disp-802',
    bookingId: 'BK-9854',
    customerName: 'Meera Deshmukh',
    workerName: 'Anand Shinde',
    service: 'Door Lock Repair',
    amount: 399,
    date: '2026-08-18',
    issueCategory: 'Billing Transparency',
    description: 'Additional hardware charge of ₹120 charged on site.',
    workerStatement: 'Uploaded merchant invoice for brass cylinder lock replaced with customer oral consent.',
    status: 'resolved_mutual',
    verdict: 'Cooperative reimbursed ₹120 hardware cost from warranty pool. 5-star rating restored to worker.'
  }
];

export const COOP_WELFARE_METRICS = {
  totalReserveFund: 1485200, // ₹14.85 Lakhs
  healthInsuranceClaimsSettled: 42,
  toolSubsidiesDisbursed: 118,
  emergencyFamilyAssistanceDisbursed: 18,
  averageWorkerHourlyUplift: 38.4, // +38.4% compared to standard aggregators
  platformTakeRate: 5.2, // only 5.2%
  workerTakeRate: 87.8,
  welfareTakeRate: 7.0,
  activeCooperativesFederated: 24,
  pacsConnectedCount: 68
};

export const MINISTRY_STATS = {
  registeredCooperatives: 148,
  totalRegisteredGigCooperatives: 148,
  nationalRegisteredCooperatives: 148,
  activeWorkers: 18450,
  totalEmpoweredWorkers: 18450,
  totalEmpoweredArtisans: 18450,
  welfareReserveFund: 1485200,
  patronageDividendsDistributed: 4280000,
  totalPatronageDividendsDistributed: 4280000,
  totalDividendsPaidOutToDate: 42800000, // ₹4.28 Crores
  capitalReturnedToWorkersCr: 84.6,
  intermediaryCommissionSavedCr: 19.8,
  nationalAverageSatisfaction: 4.88,
  stateCoverage: [
    { state: 'Maharashtra', cooperatives: 48, workers: 6200, welfareFund: '₹1.8 Cr', compliance: '98%' },
    { state: 'Karnataka', cooperatives: 32, workers: 4100, welfareFund: '₹1.2 Cr', compliance: '96%' },
    { state: 'Gujarat', cooperatives: 28, workers: 3800, welfareFund: '₹95 Lakh', compliance: '99%' },
    { state: 'Delhi NCR', cooperatives: 20, workers: 2600, welfareFund: '₹75 Lakh', compliance: '94%' },
    { state: 'Tamil Nadu', cooperatives: 14, workers: 1750, welfareFund: '₹58 Lakh', compliance: '97%' }
  ],
  commercialVsCoopComparison: {
    aggregatorWorkerCut: '65-72%',
    coopWorkerCut: '88-92%',
    aggregatorHealthCover: 'Conditional / Zero',
    coopHealthCover: '100% Guaranteed Cooperative Health Pool',
    governanceModel: 'Algorithmic Bans vs Democratic Peer Jury'
  }
};
